FROM {{.Image}}

USER root

ARG SRC_DIR=/tmp/src
COPY . $SRC_DIR

RUN for pipeline in $(ls $SRC_DIR/pipelines); do \
        cd $SRC_DIR/pipelines/$pipeline && \
        go mod tidy && \
        CGO_ENABLED=0 go build -o /data/pipelines/bin/$pipeline ./...; \
    done && \
    rm -rf $SRC_DIR

USER cacidy
